### ISSUE TITLE
Deploying not working

### ISSUE THREAD

**Issue by rehle65** [jiuka/checkmk_veeam_o365#2]
Hi,

I use the latest Enterprise Edition of checkmk and just installed this extension. I created a rule to deploy the plugin, but unfortunately the plugin never makes it to the Backup Server. Checkmk is running under Debian 10.

Any hints are highly appreciated.
Regards,
Roland

**Comment by jiuka** [comment]
Hi Roland,

I do not have any experience with the automatic deployment. However when i create a rule and the bake the agents the agent `.msi` for this host includes the plugin. Have you checked if the Agent has been baked and updated (automaticaly or manualy) on the backup server? If so check if the plugin file `veeam_o365_status.ps1` is installed on the server.

**Comment by rehle65** [comment]
Hi Markus,
thank you very much for your response. I seem to have found the root cause. The ps1 file did not make it onto the checkmk Server during the installation process. I will try a different approach and keep you posted.
Regards,
Roland

**Comment by rehle65** [comment]
Hi Markus,
I was able to identify the root cause: The installation of the mkp package did not copy the files needed for the agent (there was nothing under agents/windows/plugins). I manually copied the files and now everything works fine. Thank you for your work and your support!
Regards,
Roland

**Comment by xTrekStorex** [comment]
Just to follow up on this as I have encountered the same issue:
All 3 released .mkp files up to this point are missing the agents section of the project.
To fix this just create a tarball of the agents folder and add it to the .mkp via 7zip etc (mkp is just tar in tar).
