### ISSUE TITLE
2.7.0 Install Error

### ISSUE THREAD

**Issue by LMS235** [jiuka/checkmk_veeam_o365#23]
Installation directly in version 2.2.0p27 in preparation for the upgrade to 2.3.0p7, i.e. enabled but not active (see https://docs.checkmk.com/latest/de/mkps.html#enabled_inactive)

![image](https://github.com/jiuka/checkmk_veeam_o365/assets/8693550/5022d5a1-5ba4-4d36-9722-ea95f9c83530)

Text:
`
This package cannot be uploaded: 1 validation error for Manifest files -> __key__ value is not a valid enumeration member; permitted: 'ec_rule_packs', 'agent_based', 'checks', 'inventory', 'checkman', 'agents', 'notifications', 'gui', 'web', 'pnp-templates', 'doc', 'locales', 'bin', 'lib', 'mibs', 'alert_handlers' (type=type_error.enum; enum_values=[<PackagePart.EC_RULE_PACKS: 'ec_rule_packs'>, <PackagePart.AGENT_BASED: 'agent_based'>, <PackagePart.CHECKS: 'checks'>, <PackagePart.HASI: 'inventory'>, <PackagePart.CHECKMAN: 'checkman'>, <PackagePart.AGENTS: 'agents'>, <PackagePart.NOTIFICATIONS: 'notifications'>, <PackagePart.GUI: 'gui'>, <PackagePart.WEB: 'web'>, <PackagePart.PNP_TEMPLATES: 'pnp-templates'>, <PackagePart.DOC: 'doc'>, <PackagePart.LOCALES: 'locales'>, <PackagePart.BIN: 'bin'>, <PackagePart.LIB: 'lib'>, <PackagePart.MIBS: 'mibs'>, <PackagePart.ALERT_HANDLERS: 'alert_handlers'>])
`

**Comment by jiuka** [comment]
Version 2.7.0 only works on Checkmk 2.3.0. YOu need to update Checkmk first and then update the extension.

**Comment by LMS235** [comment]
Isn't the point of "Enabled (inactive on this site)" versions that I can install plugin updates before the upgrade?

But if this wasn't built in here, it will just have to go the "old" way.
