### ISSUE TITLE
Job name changed after CheckMK update 2.2.0p35 to 2.3.0p18

### ISSUE THREAD

**Issue by insanity67** [jiuka/checkmk_veeam_o365#27]
Hi,

I just updated CheckMK from 2.2.0p35 to 2.3.0p18, and with this veeam_o365-2.6.1.mkp to veeam_o365-2.7.1.mkp on a cloned instance for testing.

Everything works so far, but the name of the discovered check changed (I did not touch the veeam_o365_status.ps1 file on the server, looks the same for 2.6.1 and 2.7.1):

![image](https://github.com/user-attachments/assets/7f318809-0f79-4bad-a4d4-87dc0aeedc0b)

Is this an intended change? What would happen, if there are multiple jobs defined on the server?

Thanks for your great work!

**Comment by insanity67** [comment]
Looks like multiple jobs are no problem, looks like the name marked as 2 is used for the job:

![image](https://github.com/user-attachments/assets/0ed53d4e-8681-4597-a014-9f4a6e57043f)

**Comment by jiuka** [comment]
Hi @insanity67 

There are setting "Veeam for Office 365 Job Discovery" to configure how the Service is named.

Regards Marius

**Comment by insanity67** [comment]
Great, thank you very much! I hadn't even thought that far ahead...
