### ISSUE TITLE
Agent crash in 2.0.0P3

### ISSUE THREAD

**Issue by NordloSydost-Pajje** [jiuka/checkmk_veeam_o365#3]
Hi,

I get a pythoncrash in Chech_mk RAW 2.0.0p3 when it check Veeam O365 Licenses.

ValueError (could not convert string to float: 'xxxxxxxxx,xxxxxxxx')

I dont know if it is beaquse the server has Swedish Region settings where we have a , as devicer for decimal values, ex 5,1 instead of 5.1)
![wfica32_IZESQ4dqNp](https://user-images.githubusercontent.com/49557334/115743191-b8be5980-a391-11eb-88e0-aa9462c0800b.png)

**Comment by jiuka** [comment]
Hi,

Would you mind to test the fix from 31ad6c2. Sub-second precision for the license lifetime is not needed i am sure.

Regards Marius

**Comment by NordloSydost-Pajje** [comment]
The fix is working!

Thank you for the quick help!
