### ISSUE TITLE
check_mk-veeam_o365jobs check crashed version 2.2

### ISSUE THREAD

**Issue by n00rm** [jiuka/checkmk_veeam_o365#5]
![image](https://user-images.githubusercontent.com/31599944/117142426-fbc7f600-adaf-11eb-8428-0949fe4e716a.png)

Hi, 
I'm currently using the Checkmk CEE 2.0.0p3 on Ubuntu Server LTS 20.04 and the check_mk-veeam_o365jobs check is crashing. 
Is it a bug or is there something wrong with my implementation?

Thanks in advance!

Norm

**Comment by jiuka** [comment]
Hi @n00rm 

What is the locale set on the server running the `veeam_o365_status.ps1` plugin?

Regards Marius

**Comment by jiuka** [comment]
Hi @n00rm 

Could you may try if thepatch from 3f7da13 helps?

Regards Marius

**Comment by n00rm** [comment]
Hi @jiuka 



> Hi @n00rm
> 
> What is the locale set on the server running the `veeam_o365_status.ps1` plugin?
> 
> Regards Marius

The system locale is set to german.




> Hi @n00rm
> 
> Could you may try if thepatch from [3f7da13](https://github.com/jiuka/checkmk_veeam_o365/commit/3f7da13107bff66188b715fb62da814cf0f29bde) helps?
> 
> Regards Marius

I tried this patch and it's working now! Thanks for the quick help!
